
version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: users 
      MYSQL_ROOT_PASSWORD: root   
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -proot"]
        interval: 10s
        timeout: 5s
        retries: 3
    volumes:    
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - test
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
        DB_HOST: mysql
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: users
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - test

volumes:
  sql:

networks:
  test:
    driver: bridge